const interestsList = {
    "Beach",
    "Football",
    "Gambling",
    "Bars",
    "Museum",
    "Hiking",
    "Biking",
    "Shopping",
    "Bowling",
    "Dancing",
    "Fishing",
    "Movie",
    "Picnic",
    "Reading",
    "Running",
    "Swimming",
    "Traveling",
    "Video games",
    "Volunteering",
    "Yoga",
    "Board games",
    "Cooking",
    "Crafts",
    "Gardening",
    "Painting",
    "Photography",
    "Sculpture",
    "Singing",
    "Writing", 
}